fixtures:
  forge_modules:
    apt:
      repo: "puppetlabs/apt"
      ref:  "7.3.0"
    apache:
      repo: "puppetlabs/apache"
      ref:  "5.4.0"
    augeas_core:
      repo: "puppetlabs/augeas_core"
      ref:  "1.0.5"
    concat:
      repo: "puppetlabs/concat"
      ref:  "6.2.0"
    cron_core:
      repo: "puppetlabs/cron_core"
      ref:  "1.0.3"
    debconf:
      repo: "stm/debconf"
      ref:  "3.0.0"
    epel:
      repo: "stahnma/epel"
      ref:  "1.3.0"
    firewall:
      repo: "puppetlabs/firewall"
      ref:  "2.2.0"
    puppetserver_gem:
      repo: "puppetlabs/puppetserver_gem"
      ref:  "1.1.1"
    git:
      repo: "theforeman/git"
      ref:  "6.0.1"
    hosts:
      repo: "chrekh/hosts"
      ref:  "2.3.1"
    inifile:
      repo: "puppetlabs/inifile"
      ref:  "4.1.0"
    postgresql:
      repo: "puppetlabs/postgresql"
      ref:  "6.3.0"
    puppet:
      repo: "theforeman/puppet"
      ref:  "12.1.0"
    puppet_authorization:
      repo: "puppetlabs/puppet_authorization"
      ref:  "0.5.0"
    puppetboard:
      repo: "puppet/puppetboard"
      ref:  "6.0.0"
    puppetdb:
      repo: "puppetlabs/puppetdb"
      ref:  "7.4.0"
    python:
      repo: "puppet/python"
      ref:  "4.0.0"
    r10k:
      repo: "puppet/r10k"
      ref:  "8.0.0"
    sshkeys_core:
      repo: "puppetlabs/sshkeys_core"
      ref:  "1.0.3"
    stdlib:
      repo: "puppetlabs/stdlib"
      ref:  "6.2.0"
    vcsrepo:
      repo: "puppetlabs-vcsrepo"
      ref:  "3.1.0"
    yumrepo_core:
      repo: "puppetlabs/yumrepo_core"
      ref:  "1.0.6"
  repositories:
    timezone:
      repo: 'https://github.com/Puppet-Finland/puppet-timezone.git'
      branch: 'puppet6'
