---
:name: default
:description: ''
:enabled: true
:log_dir: "/var/log/kafo"
:store_dir: ''
:log_name: configuration.log
:log_level: info
:no_prefix: false
:mapping: {}
:answer_file: "/home/puppetmaster/config/installer-scenarios.d/default-answers.yaml"
:installer_dir: "/home/puppetmaster"
:module_dirs:
- "/home"
- "/home/puppetmaster/modules"
:colors: true
:color_of_background: :dark
:hook_dirs: []
:custom: {}
:low_priority_modules: []
:verbose_log_level: info
:skip_puppet_version_check: true
:password: UzbX6nCVLRQiW_LW6SyKQAii1ArNJHp5DFdhG0Wz2to
