# Format:
# <classname>: false - don't include this class
# <classname>: true - include and use the defaults
# <classname>:
#   <param>: <value> - include and override the default(s)
#
# See params.pp in each class for what options are available

---
puppetmaster::foreman:
  foreman_db_password: changeme
  foreman_admin_firstname: Admin
  foreman_admin_lastname: User
  foreman_admin_email: admin@example.com
  foreman_admin_password: changeme
  timezone: Europe/Helsinki
  puppetdb_database_password: changeme
  foreman_plugin_cockpit: false
  foreman_compute_vmware: false
  foreman_compute_libvirt: false
  foreman_compute_ec2: false
  foreman_compute_gce: false
  foreman_compute_openstack: false
  foreman_compute_ovirt: false
  foreman_compute_rackspace: false
  foreman_plugin_ansible: false
  foreman_plugin_docker: false
  foreman_plugin_bootdisk: false
  foreman_plugin_default_hostgroup: false
  foreman_plugin_dhcp_browser: false
  foreman_plugin_digitalocean: false
  foreman_plugin_discovery: false
  foreman_plugin_hooks: false
  foreman_plugin_memcache: false
  foreman_plugin_remote_execution: false
  foreman_plugin_tasks: false
  foreman_plugin_templates: false
