# Format:
# <classname>: false - don't include this class
# <classname>: true - include and use the defaults
# <classname>:
#   <param>: <value> - include and override the default(s)
#
# See params.pp in each class for what options are available

---
foreman:
  foreman_url: https://puppetserver-xenial.local
  puppetrun: false
  unattended: true
  unattended_url: 
  authentication: true
  passenger: true
  passenger_ruby: "/usr/bin/foreman-ruby"
  passenger_ruby_package: 
  plugin_prefix: ruby-foreman-
  use_vhost: true
  servername: puppetserver-xenial.local
  serveraliases:
  - foreman
  ssl: true
  custom_repo: false
  repo: stable
  configure_epel_repo: false
  configure_scl_repo: false
  selinux: 
  gpgcheck: true
  version: present
  plugin_version: present
  db_manage: true
  db_type: postgresql
  db_adapter: 
  db_host: 
  db_port: 
  db_database: 
  db_username: foreman
  db_password: c48qAjSycbXkMrMDGsw4W8SqWXyxCPLb
  db_sslmode: 
  db_root_cert: 
  db_pool: 5
  db_manage_rake: true
  app_root: "/usr/share/foreman"
  manage_user: true
  user: foreman
  group: foreman
  user_groups:
  - puppet
  rails_env: production
  puppet_home: "/var/lib/puppet"
  puppet_ssldir: "/etc/puppetlabs/puppet/ssl"
  locations_enabled: false
  organizations_enabled: false
  passenger_interface: 
  vhost_priority: '05'
  server_port: 80
  server_ssl_port: 443
  server_ssl_ca: "/etc/puppetlabs/puppet/ssl/certs/ca.pem"
  server_ssl_chain: "/etc/puppetlabs/puppet/ssl/certs/ca.pem"
  server_ssl_cert: "/etc/puppetlabs/puppet/ssl/certs/puppetserver-xenial.local.pem"
  server_ssl_certs_dir: ''
  server_ssl_key: "/etc/puppetlabs/puppet/ssl/private_keys/puppetserver-xenial.local.pem"
  server_ssl_crl: "/etc/puppetlabs/puppet/ssl/crl.pem"
  server_ssl_protocol: 
  client_ssl_ca: "/etc/puppetlabs/puppet/ssl/certs/ca.pem"
  client_ssl_cert: "/etc/puppetlabs/puppet/ssl/certs/puppetserver-xenial.local.pem"
  client_ssl_key: "/etc/puppetlabs/puppet/ssl/private_keys/puppetserver-xenial.local.pem"
  keepalive: true
  max_keepalive_requests: 100
  keepalive_timeout: 5
  oauth_active: true
  oauth_map_users: false
  oauth_consumer_key: Csp3UPZYBEghUfSnhtqsvvDu3Me4QgfJ
  oauth_consumer_secret: 5sWqoWPhCk9aHJq5TbhkWsoCw5tmxzCJ
  passenger_prestart: true
  passenger_min_instances: 1
  passenger_start_timeout: 90
  admin_username: admin
  admin_password: CtrfeBWxckckrpHq
  admin_first_name: 
  admin_last_name: 
  admin_email: 
  initial_organization: 
  initial_location: 
  ipa_authentication: false
  http_keytab: "/etc/httpd/conf/http.keytab"
  pam_service: foreman
  ipa_manage_sssd: true
  websockets_encrypt: true
  websockets_ssl_key: "/etc/puppetlabs/puppet/ssl/private_keys/puppetserver-xenial.local.pem"
  websockets_ssl_cert: "/etc/puppetlabs/puppet/ssl/certs/puppetserver-xenial.local.pem"
  logging_level: info
  loggers: {}
  email_config_method: file
  email_conf: email.yaml
  email_source: email.yaml.erb
  email_delivery_method: 
  email_smtp_address: 
  email_smtp_port: 25
  email_smtp_domain: 
  email_smtp_authentication: none
  email_smtp_user_name: 
  email_smtp_password: 
  dynflow_pool_size: 5
  jobs_service: 
  dynflow_in_core: true
  hsts_enabled: true
