---
:name: Smart Proxy
:description: install foreman-proxy and connect to foreman instance
:enabled: true
:log_dir: "/var/log/kafo"
:store_dir: ''
:log_name: configuration.log
:log_level: info
:no_prefix: false
:mapping: {}
:answer_file: "./config/installer-scenarios.d/foreman-proxy-answers.yaml"
:installer_dir: "."
:module_dirs:
- "/home/puppetmaster/modules"
- "/home"
:colors: true
:color_of_background: :dark
:hook_dirs: []
:custom: {}
:low_priority_modules: []
:verbose_log_level: info
:skip_puppet_version_check: false
:password: UGi1m8QKCX-0jRjHBF2B189MaVtPfwJ83mAURXjkp68
