# Format:
# <classname>: false - don't include this class
# <classname>: true - include and use the defaults
# <classname>:
#   <param>: <value> - include and override the default(s)
#
# See params.pp in each class for what options are available

---
puppetmaster::lcm:
  foreman_db_password: qwerty
  foreman_initial_admin_firstname: admin
  foreman_initial_admin_lastname: admin
  foreman_initial_admin_email: admin@example.org
  foreman_initial_admin_password: admin
  foreman_initial_organization: Foo Bar
  foreman_initial_location: Turku
  puppetdb_database_password: qwerty
  foreman_plugin_cockpit: false
  foreman_compute_vmware: false
  foreman_compute_libvirt: false
  foreman_compute_ec2: false
  foreman_compute_gce: false
  foreman_compute_openstack: false
  foreman_compute_ovirt: false
  foreman_compute_rackspace: false
  foreman_plugin_azure: false
  foreman_plugin_ansible: false
  foreman_plugin_docker: false
  foreman_plugin_bootdisk: false
  foreman_plugin_default_hostgroup: false
  foreman_plugin_dhcp_browser: false
  foreman_plugin_digitalocean: false
  foreman_plugin_discovery: false
  foreman_plugin_hooks: false
  foreman_plugin_memcache: false
  foreman_plugin_remote_execution: false
  foreman_plugin_tasks: false
  foreman_plugin_templates: false
  foreman_proxy_templates: false
  foreman_proxy_trusted_hosts:
  - puppet.local
  foreman_proxy_dhcp: false
  foreman_proxy_dns: false
  foreman_proxy_dhcp_managed: false
  foreman_proxy_dhcp_interface: ''
  foreman_proxy_dhcp_option_domain:
  - "[]"
  foreman_proxy_dhcp_search_domains:
  - "[]"
  foreman_proxy_dhcp_server: 'false'
  foreman_proxy_dhcp_provider: 'false'
  foreman_proxy_dhcp_subnets:
  - "[]"
  foreman_proxy_dhcp_gateway: ''
  foreman_proxy_dhcp_range: ''
  foreman_proxy_dhcp_nameservers: ''
  foreman_proxy_dhcp_pxeserver: ''
  foreman_proxy_dns_managed: false
  foreman_proxy_dns_forwarders:
  - "[]"
  foreman_proxy_dns_interface: ''
  foreman_proxy_dns_listen_on: ''
  foreman_proxy_dns_provider: ''
  foreman_proxy_dns_zone: ''
  foreman_proxy_dns_reverse: ''
  foreman_proxy_dns_server: ''
  foreman_proxy_dns_ttl: 8600
  foreman_proxy_tftp: false
  foreman_proxy_tftp_managed: false
  foreman_proxy_tftp_servername: ''
  foreman_proxy_tftp_manage_wget: false
  foreman_proxy_bmc: false
  foreman_proxy2_hostnames:
  - "[]"
  foreman_proxy2_ipaddress: ''
  foreman_proxy3_hostnames:
  - "[]"
  foreman_proxy3_ipaddress: ''
  foreman_proxy4_hostnames:
  - "[]"
  foreman_proxy4_ipaddress: ''
  timezone: Etc/UTC
  manage_packetfilter: false
