# Format:
# <classname>: false - don't include this class
# <classname>: true - include and use the defaults
# <classname>:
#   <param>: <value> - include and override the default(s)
#
# See params.pp in each class for what options are available

---
puppetmaster::lcm:
  foreman_db_password: changeme
  foreman_admin_firstname: Admin
  foreman_admin_lastname: User
  foreman_admin_email: admin@example.com
  foreman_admin_password: changeme
  timezone: Europe/Helsinki
  puppetdb_database_password: changeme
  primary_names:
  - puppet
  - puppet.local
  foreman_plugin_cockpit: false
  foreman_compute_vmware: true
  foreman_compute_libvirt: false
  foreman_compute_ec2: true
  foreman_compute_gce: true
  foreman_compute_openstack: false
  foreman_compute_ovirt: false
  foreman_compute_rackspace: false
  foreman_plugin_azure: true
  foreman_plugin_ansible: false
  foreman_plugin_docker: false
  foreman_plugin_bootdisk: false
  foreman_plugin_default_hostgroup: true
  foreman_plugin_dhcp_browser: false
  foreman_plugin_digitalocean: true
  foreman_plugin_discovery: false
  foreman_plugin_hooks: false
  foreman_plugin_memcache: false
  foreman_plugin_remote_execution: false
  foreman_plugin_tasks: false
  foreman_plugin_templates: false
  foreman_proxy_foreman_base_url: https://puppet.local
  foreman_proxy_templates: true
  foreman_proxy_templates_listen_on: both
  foreman_proxy_trusted_hosts:
  - puppet.local
  foreman_proxy_dhcp: false
  foreman_proxy_dhcp_listen_on: both
  foreman_proxy_dns: false
  foreman_proxy_dhcp_managed: false
  foreman_proxy_dhcp_interface: eth0
  foreman_proxy_dhcp_option_domain:
  - local
  foreman_proxy_dhcp_search_domains:
  - local
  foreman_proxy_dhcp_server: puppet.local
  foreman_proxy_dhcp_provider: isc
  foreman_proxy_dhcp_subnets:
  - 172.16.3.0/255.255.255.0
  foreman_proxy_dhcp_gateway: 172.16.3.254
  foreman_proxy_dhcp_range: 172.16.3.100 172.16.3.200
  foreman_proxy_dhcp_nameservers: 172.16.3.1
  foreman_proxy_dhcp_pxeserver: 172.16.3.106
  foreman_proxy_dns_managed: false
  foreman_proxy_dns_forwarders:
  - 8.8.8.8
  foreman_proxy_dns_interface: eth0
  foreman_proxy_dns_listen_on: both
  foreman_proxy_dns_provider: nsupdate
  foreman_proxy_dns_zone: local
  foreman_proxy_dns_reverse: 3.16.172.in-addr.arpa
  foreman_proxy_dns_server: 172.16.3.1
  foreman_proxy_dns_ttl: 86400
  foreman_proxy_tftp: false
  foreman_proxy_tftp_managed: false
  foreman_proxy_tftp_servername: 172.16.3.1
  foreman_proxy_tftp_manage_wget: true
  foreman_proxy_tftp_listen_on: both
  foreman_proxy_bmc: false
  foreman_proxy_bmc_listen_on: both
  foreman_proxy2_hostnames:
  - proxy2.local
  - proxy2
  foreman_proxy2_ipaddress: 192.168.221.205
  foreman_proxy3_hostnames:
  - proxy3.local
  - proxy3
  foreman_proxy3_ipaddress: 192.168.221.206
  foreman_proxy4_hostnames:
  - proxy4.local
  - proxy4
  foreman_proxy4_ipaddress: 192.168.221.207
