---
:name: Lifecycle Manager
:description: install foreman and foreman-proxy all-in-one
:enabled: true
:log_dir: "/var/log/kafo"
:store_dir: ''
:log_name: lcm.log
:log_level: debug
:no_prefix: false
:mapping:
  :puppetmaster_lcm:
    :dir_name: puppetmaster
    :manifest_name: lcm
:answer_file: "/usr/share/puppetmaster-installer/config/installer-scenarios.d/lcm-answers.yaml"
:installer_dir: "."
:module_dirs:
- "/usr/share/puppetmaster-installer/modules"
- "/usr/share/puppetmaster-installer"
:colors: true
:color_of_background: :dark
:hook_dirs:
- "/usr/share/puppetmaster-installer/hooks"
:custom: {}
:facts: {}
:low_priority_modules: []
:verbose_log_level: debug
:skip_puppet_version_check: false
:hiera_config: "/usr/share/puppetmaster-installer/config/hiera.yaml"
:password: UGi1m8QKCX-0jRjHBF2B189MaVtPfwJ83mAURXjkp68
