---
:name: Lifecycle Manager
:description: install foreman and foreman-proxy all-in-one
:enabled: true
:log_dir: "/var/log/kafo"
:store_dir: ''
:log_name: lcm.log
:log_level: info
:no_prefix: false
:mapping: {}
:answer_file: "./config/installer-scenarios.d/lcm-answers.yaml"
:installer_dir: "."
:module_dirs:
- "/usr/share/puppetmaster-installer/modules"
- "/home"
:colors: true
:color_of_background: :dark
:hook_dirs: []
:custom: {}
:low_priority_modules: []
:verbose_log_level: info
:skip_puppet_version_check: true
:password: UGi1m8QKCX-0jRjHBF2B189MaVtPfwJ83mAURXjkp68
