---
:name: Configuration Manager with puppetboard
:description: 'install puppetserver with puppetdb and puppetboard'
:enabled: true
:log_dir: "/var/log/kafo"
:store_dir: ''
:log_name: puppetboard.log
:log_level: info
:no_prefix: false
:mapping: {}
:answer_file: "./config/installer-scenarios.d/puppetboard-answers.yaml"
:installer_dir: "."
:module_dirs:
- "./modules"
:colors: true
:color_of_background: :dark
:hook_dirs: []
:custom: {}
:low_priority_modules: []
:verbose_log_level: info
:skip_puppet_version_check: false
:password: SViXZKG2VPl82e9tzpraJl5kKgm4JYuS1wg2UgZM5rE
