---
:name: Configuration Manager with Puppetdb
:description: install puppetserver with puppetdb
:enabled: true
:log_dir: "/var/log/kafo"
:store_dir: ''
:log_name: puppetserver-with-puppetdb-scenario.log
:log_level: info
:no_prefix: false
:mapping:
  :puppetmaster_puppetdb:
    :dir_name: puppetmaster
    :manifest_name: puppetdb
:answer_file: "/usr/share/puppetmaster-installer/config/installer-scenarios.d/puppetserver-with-puppetdb-answers.yaml"
:installer_dir: "."
:module_dirs:
- "/usr/share/puppetmaster-installer/modules"
- "/home"
:colors: true
:color_of_background: :dark
:hook_dirs:
- "/usr/share/puppetmaster-installer/hooks"
:custom: {}
:low_priority_modules: []
:verbose_log_level: info
:skip_puppet_version_check: true
:hiera_config: "/usr/share/puppetmaster-installer/config/hiera.conf"
:password: fCE6IPpKAOabDgxbw8s7S7qIGL6hgVliaL3JkrKr7IA
