---
:name: Configuration manager
:description: install vanilla puppetserver
:enabled: true
:log_dir: "/var/log/kafo"
:store_dir: ''
:log_name: puppetserver-scenario.log
:log_level: info
:no_prefix: false
:mapping: {}
:answer_file: "/usr/share/puppetmaster-installer/config/installer-scenarios.d/puppetserver-answers.yaml"
:installer_dir: "."
:module_dirs:
- "/usr/share/puppetmaster-installer/modules"
- "/home"
:colors: true
:color_of_background: :dark
:hook_dirs: []
:custom: {}
:low_priority_modules: []
:verbose_log_level: info
:skip_puppet_version_check: true
:password: fCE6IPpKAOabDgxbw8s7S7qIGL6hgVliaL3JkrKr7IA
