# Format:
# <classname>: false - don't include this class
# <classname>: true - include and use the defaults
# <classname>:
#   <param>: <value> - include and override the default(s)
#
# See params.pp in each class for what options are available

---
puppetmaster::puppetboard:
  autosign: "/etc/puppetlabs/puppet/autosign.conf"
  autosign_entries: 
  timezone: Europe/Helsinki
  puppetdb_database_password: puppetdb
